/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentSelf {
    #[serde(rename = "Config", skip_serializing_if = "Option::is_none")]
    pub config: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "Member", skip_serializing_if = "Option::is_none")]
    pub member: Option<Box<crate::models::AgentMember>>,
    #[serde(rename = "Stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, String>>>,
}

impl AgentSelf {
    pub fn new() -> AgentSelf {
        AgentSelf {
            config: None,
            member: None,
            stats: None,
        }
    }
}


