/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentMember {
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "Addr", skip_serializing_if = "Option::is_none")]
    pub addr: Option<String>,
    #[serde(rename = "Port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    #[serde(rename = "Tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "Status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "ProtocolMin", skip_serializing_if = "Option::is_none")]
    pub protocol_min: Option<i32>,
    #[serde(rename = "ProtocolMax", skip_serializing_if = "Option::is_none")]
    pub protocol_max: Option<i32>,
    #[serde(rename = "ProtocolCur", skip_serializing_if = "Option::is_none")]
    pub protocol_cur: Option<i32>,
    #[serde(rename = "DelegateMin", skip_serializing_if = "Option::is_none")]
    pub delegate_min: Option<i32>,
    #[serde(rename = "DelegateMax", skip_serializing_if = "Option::is_none")]
    pub delegate_max: Option<i32>,
    #[serde(rename = "DelegateCur", skip_serializing_if = "Option::is_none")]
    pub delegate_cur: Option<i32>,
}

impl AgentMember {
    pub fn new() -> AgentMember {
        AgentMember {
            name: None,
            addr: None,
            port: None,
            tags: None,
            status: None,
            protocol_min: None,
            protocol_max: None,
            protocol_cur: None,
            delegate_min: None,
            delegate_max: None,
            delegate_cur: None,
        }
    }
}


