/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocationRestartRequest {
    #[serde(rename = "TaskName", skip_serializing_if = "Option::is_none")]
    pub task_name: Option<String>,
}

impl AllocationRestartRequest {
    pub fn new() -> AllocationRestartRequest {
        AllocationRestartRequest {
            task_name: None,
        }
    }
}


