/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocSignalRequest {
    #[serde(rename = "Task", skip_serializing_if = "Option::is_none")]
    pub task: Option<String>,
    #[serde(rename = "Signal", skip_serializing_if = "Option::is_none")]
    pub signal: Option<String>,
}

impl AllocSignalRequest {
    pub fn new() -> AllocSignalRequest {
        AllocSignalRequest {
            task: None,
            signal: None,
        }
    }
}


