/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocatedResources {
    #[serde(rename = "Tasks", skip_serializing_if = "Option::is_none")]
    pub tasks: Option<::std::collections::HashMap<String, crate::models::AllocatedTaskResources>>,
    #[serde(rename = "Shared", skip_serializing_if = "Option::is_none")]
    pub shared: Option<Box<crate::models::AllocatedSharedResources>>,
}

impl AllocatedResources {
    pub fn new() -> AllocatedResources {
        AllocatedResources {
            tasks: None,
            shared: None,
        }
    }
}


