/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Attribute {
    #[serde(rename = "Float", skip_serializing_if = "Option::is_none")]
    pub float: Option<f64>,
    #[serde(rename = "Int", skip_serializing_if = "Option::is_none")]
    pub int: Option<i64>,
    #[serde(rename = "String", skip_serializing_if = "Option::is_none")]
    pub string: Option<String>,
    #[serde(rename = "Bool", skip_serializing_if = "Option::is_none")]
    pub bool: Option<bool>,
    #[serde(rename = "Unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl Attribute {
    pub fn new() -> Attribute {
        Attribute {
            float: None,
            int: None,
            string: None,
            bool: None,
            unit: None,
        }
    }
}


