/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConsulUpstream {
    #[serde(rename = "DestinationName", skip_serializing_if = "Option::is_none")]
    pub destination_name: Option<String>,
    #[serde(rename = "LocalBindPort", skip_serializing_if = "Option::is_none")]
    pub local_bind_port: Option<i32>,
}

impl ConsulUpstream {
    pub fn new() -> ConsulUpstream {
        ConsulUpstream {
            destination_name: None,
            local_bind_port: None,
        }
    }
}


