/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConsulConnect {
    #[serde(rename = "Native", skip_serializing_if = "Option::is_none")]
    pub native: Option<bool>,
    #[serde(rename = "SidecarService", skip_serializing_if = "Option::is_none")]
    pub sidecar_service: Option<Box<crate::models::ConsulSidecarService>>,
    #[serde(rename = "SidecarTask", skip_serializing_if = "Option::is_none")]
    pub sidecar_task: Option<Box<crate::models::SidecarTask>>,
}

impl ConsulConnect {
    pub fn new() -> ConsulConnect {
        ConsulConnect {
            native: None,
            sidecar_service: None,
            sidecar_task: None,
        }
    }
}


