/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CsiNodeInfo {
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub ID: Option<String>,
    #[serde(rename = "MaxVolumes", skip_serializing_if = "Option::is_none")]
    pub max_volumes: Option<i64>,
    #[serde(rename = "AccessibleTopology", skip_serializing_if = "Option::is_none")]
    pub accessible_topology: Option<Box<crate::models::CsiTopology>>,
    #[serde(rename = "RequiresNodeStageVolume", skip_serializing_if = "Option::is_none")]
    pub requires_node_stage_volume: Option<bool>,
}

impl CsiNodeInfo {
    pub fn new() -> CsiNodeInfo {
        CsiNodeInfo {
            ID: None,
            max_volumes: None,
            accessible_topology: None,
            requires_node_stage_volume: None,
        }
    }
}


