/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentFailRequest {
    #[serde(rename = "DeploymentID", skip_serializing_if = "Option::is_none")]
    pub deployment_id: Option<String>,
}

impl DeploymentFailRequest {
    pub fn new() -> DeploymentFailRequest {
        DeploymentFailRequest {
            deployment_id: None,
        }
    }
}


