/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostCpuStats {
    #[serde(rename = "Cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<String>,
    #[serde(rename = "User", skip_serializing_if = "Option::is_none")]
    pub user: Option<f64>,
    #[serde(rename = "System", skip_serializing_if = "Option::is_none")]
    pub system: Option<f64>,
    #[serde(rename = "Idle", skip_serializing_if = "Option::is_none")]
    pub idle: Option<f64>,
}

impl HostCpuStats {
    pub fn new() -> HostCpuStats {
        HostCpuStats {
            cpu: None,
            user: None,
            system: None,
            idle: None,
        }
    }
}


