/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostMemoryStats {
    #[serde(rename = "Total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "Available", skip_serializing_if = "Option::is_none")]
    pub available: Option<i32>,
    #[serde(rename = "Used", skip_serializing_if = "Option::is_none")]
    pub used: Option<i32>,
    #[serde(rename = "Free", skip_serializing_if = "Option::is_none")]
    pub free: Option<i32>,
}

impl HostMemoryStats {
    pub fn new() -> HostMemoryStats {
        HostMemoryStats {
            total: None,
            available: None,
            used: None,
            free: None,
        }
    }
}


