/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobEvaluateRequest {
    #[serde(rename = "JobID")]
    pub job_id: String,
    #[serde(rename = "EvalOptions", skip_serializing_if = "Option::is_none")]
    pub eval_options: Option<Box<crate::models::EvalOptions>>,
}

impl JobEvaluateRequest {
    pub fn new(job_id: String) -> JobEvaluateRequest {
        JobEvaluateRequest {
            job_id,
            eval_options: None,
        }
    }
}


