/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobSummary {
    #[serde(rename = "JobID", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<String>,
    #[serde(rename = "Namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "Summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<::std::collections::HashMap<String, crate::models::TaskGroupSummary>>,
    #[serde(rename = "Children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Box<crate::models::JobChildrenSummary>>,
    #[serde(rename = "CreateIndex", skip_serializing_if = "Option::is_none")]
    pub create_index: Option<i32>,
    #[serde(rename = "ModifyIndex", skip_serializing_if = "Option::is_none")]
    pub modify_index: Option<i32>,
}

impl JobSummary {
    pub fn new() -> JobSummary {
        JobSummary {
            job_id: None,
            namespace: None,
            summary: None,
            children: None,
            create_index: None,
            modify_index: None,
        }
    }
}


