/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Port {
    #[serde(rename = "Label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "Value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i32>,
    #[serde(rename = "To", skip_serializing_if = "Option::is_none")]
    pub to: Option<i32>,
}

impl Port {
    pub fn new() -> Port {
        Port {
            label: None,
            value: None,
            to: None,
        }
    }
}


