/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReschedulePolicy {
    #[serde(rename = "Attempts", skip_serializing_if = "Option::is_none")]
    pub attempts: Option<i32>,
    #[serde(rename = "Interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<i64>,
    #[serde(rename = "Delay", skip_serializing_if = "Option::is_none")]
    pub delay: Option<i64>,
    #[serde(rename = "DelayFunction", skip_serializing_if = "Option::is_none")]
    pub delay_function: Option<String>,
    #[serde(rename = "MaxDelay", skip_serializing_if = "Option::is_none")]
    pub max_delay: Option<i64>,
    #[serde(rename = "Unlimited", skip_serializing_if = "Option::is_none")]
    pub unlimited: Option<bool>,
}

impl ReschedulePolicy {
    pub fn new() -> ReschedulePolicy {
        ReschedulePolicy {
            attempts: None,
            interval: None,
            delay: None,
            delay_function: None,
            max_delay: None,
            unlimited: None,
        }
    }
}


