/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchedulerSetConfigurationResponse {
    #[serde(rename = "Updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<bool>,
}

impl SchedulerSetConfigurationResponse {
    pub fn new() -> SchedulerSetConfigurationResponse {
        SchedulerSetConfigurationResponse {
            updated: None,
        }
    }
}


