/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchResponse {
    #[serde(rename = "Matches", skip_serializing_if = "Option::is_none")]
    pub matches: Option<::std::collections::HashMap<String, Vec<String>>>,
    #[serde(rename = "Truncations", skip_serializing_if = "Option::is_none")]
    pub truncations: Option<::std::collections::HashMap<String, bool>>,
}

impl SearchResponse {
    pub fn new() -> SearchResponse {
        SearchResponse {
            matches: None,
            truncations: None,
        }
    }
}


