/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatValue {
    #[serde(rename = "FloatNumeratorVal", skip_serializing_if = "Option::is_none")]
    pub float_numerator_val: Option<f64>,
    #[serde(rename = "FloatDenominatorVal", skip_serializing_if = "Option::is_none")]
    pub float_denominator_val: Option<f64>,
    #[serde(rename = "IntNumeratorVal", skip_serializing_if = "Option::is_none")]
    pub int_numerator_val: Option<i64>,
    #[serde(rename = "IntDenominatorVal", skip_serializing_if = "Option::is_none")]
    pub int_denominator_val: Option<i64>,
    #[serde(rename = "StringVal", skip_serializing_if = "Option::is_none")]
    pub string_val: Option<String>,
    #[serde(rename = "BoolVal", skip_serializing_if = "Option::is_none")]
    pub bool_val: Option<bool>,
    #[serde(rename = "Unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(rename = "Desc", skip_serializing_if = "Option::is_none")]
    pub desc: Option<String>,
}

impl StatValue {
    pub fn new() -> StatValue {
        StatValue {
            float_numerator_val: None,
            float_denominator_val: None,
            int_numerator_val: None,
            int_denominator_val: None,
            string_val: None,
            bool_val: None,
            unit: None,
            desc: None,
        }
    }
}


