/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StreamFrame {
    #[serde(rename = "Offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(rename = "Data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    #[serde(rename = "File", skip_serializing_if = "Option::is_none")]
    pub file: Option<String>,
    #[serde(rename = "FileEvent", skip_serializing_if = "Option::is_none")]
    pub file_event: Option<String>,
}

impl StreamFrame {
    pub fn new() -> StreamFrame {
        StreamFrame {
            offset: None,
            data: None,
            file: None,
            file_event: None,
        }
    }
}


