/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskLifecycle {
    #[serde(rename = "Hook", skip_serializing_if = "Option::is_none")]
    pub hook: Option<String>,
    #[serde(rename = "Sidecar", skip_serializing_if = "Option::is_none")]
    pub sidecar: Option<bool>,
}

impl TaskLifecycle {
    pub fn new() -> TaskLifecycle {
        TaskLifecycle {
            hook: None,
            sidecar: None,
        }
    }
}


