/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskResourceUsage {
    #[serde(rename = "ResourceUsage", skip_serializing_if = "Option::is_none")]
    pub resource_usage: Option<Box<crate::models::ResourceUsage>>,
    #[serde(rename = "Timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(rename = "Pids", skip_serializing_if = "Option::is_none")]
    pub pids: Option<::std::collections::HashMap<String, crate::models::ResourceUsage>>,
}

impl TaskResourceUsage {
    pub fn new() -> TaskResourceUsage {
        TaskResourceUsage {
            resource_usage: None,
            timestamp: None,
            pids: None,
        }
    }
}


