/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentHealthResponse {
    #[serde(rename = "Client", skip_serializing_if = "Option::is_none")]
    pub client: Option<Box<crate::models::AgentHealth>>,
    #[serde(rename = "Server", skip_serializing_if = "Option::is_none")]
    pub server: Option<Box<crate::models::AgentHealth>>,
}

impl AgentHealthResponse {
    pub fn new() -> AgentHealthResponse {
        AgentHealthResponse {
            client: None,
            server: None,
        }
    }
}


