/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocationMetric {
    #[serde(rename = "NodesEvaluated", skip_serializing_if = "Option::is_none")]
    pub nodes_evaluated: Option<i32>,
    #[serde(rename = "NodesFiltered", skip_serializing_if = "Option::is_none")]
    pub nodes_filtered: Option<i32>,
    #[serde(rename = "NodesAvailable", skip_serializing_if = "Option::is_none")]
    pub nodes_available: Option<::std::collections::HashMap<String, i32>>,
    #[serde(rename = "ClassFiltered", skip_serializing_if = "Option::is_none")]
    pub class_filtered: Option<::std::collections::HashMap<String, i32>>,
    #[serde(rename = "ConstraintFiltered", skip_serializing_if = "Option::is_none")]
    pub constraint_filtered: Option<::std::collections::HashMap<String, i32>>,
    #[serde(rename = "NodesExhausted", skip_serializing_if = "Option::is_none")]
    pub nodes_exhausted: Option<i32>,
    #[serde(rename = "ClassExhausted", skip_serializing_if = "Option::is_none")]
    pub class_exhausted: Option<::std::collections::HashMap<String, i32>>,
    #[serde(rename = "DimensionExhausted", skip_serializing_if = "Option::is_none")]
    pub dimension_exhausted: Option<::std::collections::HashMap<String, i32>>,
    #[serde(rename = "QuotaExhausted", skip_serializing_if = "Option::is_none")]
    pub quota_exhausted: Option<Vec<String>>,
    #[serde(rename = "Scores", skip_serializing_if = "Option::is_none")]
    pub scores: Option<::std::collections::HashMap<String, f64>>,
    #[serde(rename = "AllocationTime", skip_serializing_if = "Option::is_none")]
    pub allocation_time: Option<i64>,
    #[serde(rename = "CoalescedFailures", skip_serializing_if = "Option::is_none")]
    pub coalesced_failures: Option<i32>,
    #[serde(rename = "ScoreMetaData", skip_serializing_if = "Option::is_none")]
    pub score_meta_data: Option<Vec<crate::models::NodeScoreMeta>>,
}

impl AllocationMetric {
    pub fn new() -> AllocationMetric {
        AllocationMetric {
            nodes_evaluated: None,
            nodes_filtered: None,
            nodes_available: None,
            class_filtered: None,
            constraint_filtered: None,
            nodes_exhausted: None,
            class_exhausted: None,
            dimension_exhausted: None,
            quota_exhausted: None,
            scores: None,
            allocation_time: None,
            coalesced_failures: None,
            score_meta_data: None,
        }
    }
}


