/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocatedMemoryResources {
    #[serde(rename = "MemoryMB", skip_serializing_if = "Option::is_none")]
    pub memory_mb: Option<i64>,
}

impl AllocatedMemoryResources {
    pub fn new() -> AllocatedMemoryResources {
        AllocatedMemoryResources {
            memory_mb: None,
        }
    }
}


