/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckRestart {
    #[serde(rename = "Limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "Grace", skip_serializing_if = "Option::is_none")]
    pub grace: Option<i64>,
    #[serde(rename = "IgnoreWarnings", skip_serializing_if = "Option::is_none")]
    pub ignore_warnings: Option<bool>,
}

impl CheckRestart {
    pub fn new() -> CheckRestart {
        CheckRestart {
            limit: None,
            grace: None,
            ignore_warnings: None,
        }
    }
}


