/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConsulProxy {
    #[serde(rename = "LocalServiceAddress", skip_serializing_if = "Option::is_none")]
    pub local_service_address: Option<String>,
    #[serde(rename = "LocalServicePort", skip_serializing_if = "Option::is_none")]
    pub local_service_port: Option<i32>,
    #[serde(rename = "Upstreams", skip_serializing_if = "Option::is_none")]
    pub upstreams: Option<Vec<crate::models::ConsulUpstream>>,
    #[serde(rename = "Config", skip_serializing_if = "Option::is_none")]
    pub config: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl ConsulProxy {
    pub fn new() -> ConsulProxy {
        ConsulProxy {
            local_service_address: None,
            local_service_port: None,
            upstreams: None,
            config: None,
        }
    }
}


