/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConsulSidecarService {
    #[serde(rename = "Tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "Port", skip_serializing_if = "Option::is_none")]
    pub port: Option<String>,
    #[serde(rename = "Proxy", skip_serializing_if = "Option::is_none")]
    pub proxy: Option<Box<crate::models::ConsulProxy>>,
}

impl ConsulSidecarService {
    pub fn new() -> ConsulSidecarService {
        ConsulSidecarService {
            tags: None,
            port: None,
            proxy: None,
        }
    }
}


