/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Constraint {
    #[serde(rename = "LTarget", skip_serializing_if = "Option::is_none")]
    pub l_target: Option<String>,
    #[serde(rename = "RTarget", skip_serializing_if = "Option::is_none")]
    pub r_target: Option<String>,
    #[serde(rename = "Operand", skip_serializing_if = "Option::is_none")]
    pub operand: Option<String>,
}

impl Constraint {
    pub fn new() -> Constraint {
        Constraint {
            l_target: None,
            r_target: None,
            operand: None,
        }
    }
}


