/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CsiMountOptions {
    #[serde(rename = "FsType", skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,
    #[serde(rename = "MountFlags", skip_serializing_if = "Option::is_none")]
    pub mount_flags: Option<Vec<String>>,
}

impl CsiMountOptions {
    pub fn new() -> CsiMountOptions {
        CsiMountOptions {
            fs_type: None,
            mount_flags: None,
        }
    }
}


