/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CsiTopology {
    #[serde(rename = "Segments", skip_serializing_if = "Option::is_none")]
    pub segments: Option<::std::collections::HashMap<String, String>>,
}

impl CsiTopology {
    pub fn new() -> CsiTopology {
        CsiTopology {
            segments: None,
        }
    }
}


