/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentUpdateResponse {
    #[serde(rename = "EvalID", skip_serializing_if = "Option::is_none")]
    pub eval_id: Option<String>,
    #[serde(rename = "EvalCreateIndex", skip_serializing_if = "Option::is_none")]
    pub eval_create_index: Option<i32>,
    #[serde(rename = "DeploymentModifyIndex", skip_serializing_if = "Option::is_none")]
    pub deployment_modify_index: Option<i32>,
    #[serde(rename = "RevertedJobVersion", skip_serializing_if = "Option::is_none")]
    pub reverted_job_version: Option<i32>,
}

impl DeploymentUpdateResponse {
    pub fn new() -> DeploymentUpdateResponse {
        DeploymentUpdateResponse {
            eval_id: None,
            eval_create_index: None,
            deployment_modify_index: None,
            reverted_job_version: None,
        }
    }
}


