/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentPauseRequest {
    #[serde(rename = "DeploymentID", skip_serializing_if = "Option::is_none")]
    pub deployment_id: Option<String>,
    #[serde(rename = "Pause", skip_serializing_if = "Option::is_none")]
    pub pause: Option<bool>,
}

impl DeploymentPauseRequest {
    pub fn new() -> DeploymentPauseRequest {
        DeploymentPauseRequest {
            deployment_id: None,
            pause: None,
        }
    }
}


