/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentAllocHealthRequest {
    #[serde(rename = "DeploymentID", skip_serializing_if = "Option::is_none")]
    pub deployment_id: Option<String>,
    #[serde(rename = "HealthyAllocationIDs", skip_serializing_if = "Option::is_none")]
    pub healthy_allocation_ids: Option<Vec<String>>,
    #[serde(rename = "UnhealthyAllocationIDs", skip_serializing_if = "Option::is_none")]
    pub unhealthy_allocation_ids: Option<Vec<String>>,
}

impl DeploymentAllocHealthRequest {
    pub fn new() -> DeploymentAllocHealthRequest {
        DeploymentAllocHealthRequest {
            deployment_id: None,
            healthy_allocation_ids: None,
            unhealthy_allocation_ids: None,
        }
    }
}


