/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentState {
    #[serde(rename = "PlacedCanaries", skip_serializing_if = "Option::is_none")]
    pub placed_canaries: Option<Vec<String>>,
    #[serde(rename = "AutoRevert", skip_serializing_if = "Option::is_none")]
    pub auto_revert: Option<bool>,
    #[serde(rename = "ProgressDeadline", skip_serializing_if = "Option::is_none")]
    pub progress_deadline: Option<i64>,
    #[serde(rename = "RequireProgressBy", skip_serializing_if = "Option::is_none")]
    pub require_progress_by: Option<String>,
    #[serde(rename = "Promoted", skip_serializing_if = "Option::is_none")]
    pub promoted: Option<bool>,
    #[serde(rename = "DesiredCanaries", skip_serializing_if = "Option::is_none")]
    pub desired_canaries: Option<i32>,
    #[serde(rename = "DesiredTotal", skip_serializing_if = "Option::is_none")]
    pub desired_total: Option<i32>,
    #[serde(rename = "PlacedAllocs", skip_serializing_if = "Option::is_none")]
    pub placed_allocs: Option<i32>,
    #[serde(rename = "HealthyAllocs", skip_serializing_if = "Option::is_none")]
    pub healthy_allocs: Option<i32>,
    #[serde(rename = "UnhealthyAllocs", skip_serializing_if = "Option::is_none")]
    pub unhealthy_allocs: Option<i32>,
}

impl DeploymentState {
    pub fn new() -> DeploymentState {
        DeploymentState {
            placed_canaries: None,
            auto_revert: None,
            progress_deadline: None,
            require_progress_by: None,
            promoted: None,
            desired_canaries: None,
            desired_total: None,
            placed_allocs: None,
            healthy_allocs: None,
            unhealthy_allocs: None,
        }
    }
}


