/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceStats {
    #[serde(rename = "Summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<crate::models::StatValue>>,
    #[serde(rename = "Stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<Box<crate::models::StatObject>>,
    #[serde(rename = "Timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl DeviceStats {
    pub fn new() -> DeviceStats {
        DeviceStats {
            summary: None,
            stats: None,
            timestamp: None,
        }
    }
}


