/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DispatchPayloadConfig {
    #[serde(rename = "File", skip_serializing_if = "Option::is_none")]
    pub file: Option<String>,
}

impl DispatchPayloadConfig {
    pub fn new() -> DispatchPayloadConfig {
        DispatchPayloadConfig {
            file: None,
        }
    }
}


