/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EphemeralDisk {
    #[serde(rename = "Sticky", skip_serializing_if = "Option::is_none")]
    pub sticky: Option<bool>,
    #[serde(rename = "Migrate", skip_serializing_if = "Option::is_none")]
    pub migrate: Option<bool>,
    #[serde(rename = "SizeMB", skip_serializing_if = "Option::is_none")]
    pub size_mb: Option<i32>,
}

impl EphemeralDisk {
    pub fn new() -> EphemeralDisk {
        EphemeralDisk {
            sticky: None,
            migrate: None,
            size_mb: None,
        }
    }
}


