/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldDiff {
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "Old", skip_serializing_if = "Option::is_none")]
    pub old: Option<String>,
    #[serde(rename = "New", skip_serializing_if = "Option::is_none")]
    pub new: Option<String>,
    #[serde(rename = "Annotations", skip_serializing_if = "Option::is_none")]
    pub annotations: Option<Vec<String>>,
}

impl FieldDiff {
    pub fn new() -> FieldDiff {
        FieldDiff {
            _type: None,
            name: None,
            old: None,
            new: None,
            annotations: None,
        }
    }
}


