/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostDiskStats {
    #[serde(rename = "Device", skip_serializing_if = "Option::is_none")]
    pub device: Option<String>,
    #[serde(rename = "Mountpoint", skip_serializing_if = "Option::is_none")]
    pub mountpoint: Option<String>,
    #[serde(rename = "Size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    #[serde(rename = "Used", skip_serializing_if = "Option::is_none")]
    pub used: Option<i32>,
    #[serde(rename = "Available", skip_serializing_if = "Option::is_none")]
    pub available: Option<i32>,
    #[serde(rename = "UsedPercent", skip_serializing_if = "Option::is_none")]
    pub used_percent: Option<f64>,
    #[serde(rename = "InodesUsedPercent", skip_serializing_if = "Option::is_none")]
    pub inodes_used_percent: Option<f64>,
}

impl HostDiskStats {
    pub fn new() -> HostDiskStats {
        HostDiskStats {
            device: None,
            mountpoint: None,
            size: None,
            used: None,
            available: None,
            used_percent: None,
            inodes_used_percent: None,
        }
    }
}


