/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobStabilityRequest {
    #[serde(rename = "JobID")]
    pub job_id: String,
    #[serde(rename = "JobVersion", skip_serializing_if = "Option::is_none")]
    pub job_version: Option<i32>,
    #[serde(rename = "Stable", skip_serializing_if = "Option::is_none")]
    pub stable: Option<bool>,
}

impl JobStabilityRequest {
    pub fn new(job_id: String) -> JobStabilityRequest {
        JobStabilityRequest {
            job_id,
            job_version: None,
            stable: None,
        }
    }
}


