/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobValidateResponse {
    #[serde(rename = "DriverConfigValidated", skip_serializing_if = "Option::is_none")]
    pub driver_config_validated: Option<bool>,
    #[serde(rename = "ValidationErrors", skip_serializing_if = "Option::is_none")]
    pub validation_errors: Option<Vec<String>>,
    #[serde(rename = "Error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "Warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<String>,
}

impl JobValidateResponse {
    pub fn new() -> JobValidateResponse {
        JobValidateResponse {
            driver_config_validated: None,
            validation_errors: None,
            error: None,
            warnings: None,
        }
    }
}


