/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobPlanRequest {
    #[serde(rename = "Job")]
    pub job: Option<Box<crate::models::Job>>,
    #[serde(rename = "Diff", skip_serializing_if = "Option::is_none")]
    pub diff: Option<bool>,
    #[serde(rename = "PolicyOverride", skip_serializing_if = "Option::is_none")]
    pub policy_override: Option<bool>,
}

impl JobPlanRequest {
    pub fn new(job: Option<crate::models::Job>) -> JobPlanRequest {
        JobPlanRequest {
            job: None,
            diff: None,
            policy_override: None,
        }
    }
}


