/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobDispatchResponse {
    #[serde(rename = "DispatchedJobID", skip_serializing_if = "Option::is_none")]
    pub dispatched_job_id: Option<String>,
    #[serde(rename = "EvalID", skip_serializing_if = "Option::is_none")]
    pub eval_id: Option<String>,
    #[serde(rename = "EvalCreateIndex", skip_serializing_if = "Option::is_none")]
    pub eval_create_index: Option<i32>,
    #[serde(rename = "JobCreateIndex", skip_serializing_if = "Option::is_none")]
    pub job_create_index: Option<i32>,
}

impl JobDispatchResponse {
    pub fn new() -> JobDispatchResponse {
        JobDispatchResponse {
            dispatched_job_id: None,
            eval_id: None,
            eval_create_index: None,
            job_create_index: None,
        }
    }
}


