/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsParseRequest {
    #[serde(rename = "JobHcl")]
    pub job_hcl: String,
    #[serde(rename = "Canonicalize", skip_serializing_if = "Option::is_none")]
    pub canonicalize: Option<bool>,
}

impl JobsParseRequest {
    pub fn new(job_hcl: String) -> JobsParseRequest {
        JobsParseRequest {
            job_hcl,
            canonicalize: None,
        }
    }
}


