/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JoinResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "num_joined", skip_serializing_if = "Option::is_none")]
    pub num_joined: Option<i32>,
}

impl JoinResponse {
    pub fn new() -> JoinResponse {
        JoinResponse {
            error: None,
            num_joined: None,
        }
    }
}


