/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyringResponse {
    #[serde(rename = "Messages", skip_serializing_if = "Option::is_none")]
    pub messages: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "Keys", skip_serializing_if = "Option::is_none")]
    pub keys: Option<::std::collections::HashMap<String, i32>>,
    #[serde(rename = "NumNodes", skip_serializing_if = "Option::is_none")]
    pub num_nodes: Option<i32>,
}

impl KeyringResponse {
    pub fn new() -> KeyringResponse {
        KeyringResponse {
            messages: None,
            keys: None,
            num_nodes: None,
        }
    }
}


