/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogConfig {
    #[serde(rename = "MaxFiles", skip_serializing_if = "Option::is_none")]
    pub max_files: Option<i32>,
    #[serde(rename = "MaxFileSizeMb", skip_serializing_if = "Option::is_none")]
    pub max_file_size_mb: Option<i32>,
}

impl LogConfig {
    pub fn new() -> LogConfig {
        LogConfig {
            max_files: None,
            max_file_size_mb: None,
        }
    }
}


