/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MigrateStrategy {
    #[serde(rename = "MaxParallel", skip_serializing_if = "Option::is_none")]
    pub max_parallel: Option<i32>,
    #[serde(rename = "HealthCheck", skip_serializing_if = "Option::is_none")]
    pub health_check: Option<String>,
    #[serde(rename = "MinHealthyTime", skip_serializing_if = "Option::is_none")]
    pub min_healthy_time: Option<i64>,
    #[serde(rename = "HealthyDeadline", skip_serializing_if = "Option::is_none")]
    pub healthy_deadline: Option<i64>,
}

impl MigrateStrategy {
    pub fn new() -> MigrateStrategy {
        MigrateStrategy {
            max_parallel: None,
            health_check: None,
            min_healthy_time: None,
            healthy_deadline: None,
        }
    }
}


