/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkDns {
    #[serde(rename = "Servers", skip_serializing_if = "Option::is_none")]
    pub servers: Option<Vec<String>>,
    #[serde(rename = "Searches", skip_serializing_if = "Option::is_none")]
    pub searches: Option<Vec<String>>,
    #[serde(rename = "Options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<String>>,
}

impl NetworkDns {
    pub fn new() -> NetworkDns {
        NetworkDns {
            servers: None,
            searches: None,
            options: None,
        }
    }
}


