/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeUpdateDrainRequest {
    #[serde(rename = "NodeID", skip_serializing_if = "Option::is_none")]
    pub node_id: Option<String>,
    #[serde(rename = "DrainSpec", skip_serializing_if = "Option::is_none")]
    pub drain_spec: Option<Box<crate::models::DrainSpec>>,
    #[serde(rename = "MarkEligible", skip_serializing_if = "Option::is_none")]
    pub mark_eligible: Option<bool>,
}

impl NodeUpdateDrainRequest {
    pub fn new() -> NodeUpdateDrainRequest {
        NodeUpdateDrainRequest {
            node_id: None,
            drain_spec: None,
            mark_eligible: None,
        }
    }
}


