/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeUpdateEligibilityRequest {
    #[serde(rename = "NodeID", skip_serializing_if = "Option::is_none")]
    pub node_id: Option<String>,
    #[serde(rename = "Eligibility")]
    pub eligibility: Eligibility,
}

impl NodeUpdateEligibilityRequest {
    pub fn new(eligibility: Eligibility) -> NodeUpdateEligibilityRequest {
        NodeUpdateEligibilityRequest {
            node_id: None,
            eligibility,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Eligibility {
    #[serde(rename = "eligible")]
    Eligible,
    #[serde(rename = "ineligible")]
    Ineligible,
}

