/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeDeviceResource {
    #[serde(rename = "Vendor", skip_serializing_if = "Option::is_none")]
    pub vendor: Option<String>,
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "Instances", skip_serializing_if = "Option::is_none")]
    pub instances: Option<Vec<crate::models::NodeDevice>>,
    #[serde(rename = "Attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<::std::collections::HashMap<String, crate::models::Attribute>>,
}

impl NodeDeviceResource {
    pub fn new() -> NodeDeviceResource {
        NodeDeviceResource {
            vendor: None,
            _type: None,
            name: None,
            instances: None,
            attributes: None,
        }
    }
}


