/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeEligibilityUpdateResponse {
    #[serde(rename = "NodeModifyIndex", skip_serializing_if = "Option::is_none")]
    pub node_modify_index: Option<i32>,
    #[serde(rename = "EvalIDs", skip_serializing_if = "Option::is_none")]
    pub eval_ids: Option<Vec<String>>,
    #[serde(rename = "EvalCreateIndex", skip_serializing_if = "Option::is_none")]
    pub eval_create_index: Option<i32>,
}

impl NodeEligibilityUpdateResponse {
    pub fn new() -> NodeEligibilityUpdateResponse {
        NodeEligibilityUpdateResponse {
            node_modify_index: None,
            eval_ids: None,
            eval_create_index: None,
        }
    }
}


