/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeReservedMemoryResources {
    #[serde(rename = "MemoryMb", skip_serializing_if = "Option::is_none")]
    pub memory_mb: Option<i32>,
}

impl NodeReservedMemoryResources {
    pub fn new() -> NodeReservedMemoryResources {
        NodeReservedMemoryResources {
            memory_mb: None,
        }
    }
}


