/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParameterizedJobConfig {
    #[serde(rename = "Payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
    #[serde(rename = "MetaRequired", skip_serializing_if = "Option::is_none")]
    pub meta_required: Option<Vec<String>>,
    #[serde(rename = "MetaOptional", skip_serializing_if = "Option::is_none")]
    pub meta_optional: Option<Vec<String>>,
}

impl ParameterizedJobConfig {
    pub fn new() -> ParameterizedJobConfig {
        ParameterizedJobConfig {
            payload: None,
            meta_required: None,
            meta_optional: None,
        }
    }
}


