/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PeriodicConfig {
    #[serde(rename = "Enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "Spec", skip_serializing_if = "Option::is_none")]
    pub spec: Option<String>,
    #[serde(rename = "SpecType", skip_serializing_if = "Option::is_none")]
    pub spec_type: Option<String>,
    #[serde(rename = "ProhibitOverlap", skip_serializing_if = "Option::is_none")]
    pub prohibit_overlap: Option<bool>,
    #[serde(rename = "TimeZone", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
}

impl PeriodicConfig {
    pub fn new() -> PeriodicConfig {
        PeriodicConfig {
            enabled: None,
            spec: None,
            spec_type: None,
            prohibit_overlap: None,
            time_zone: None,
        }
    }
}


