/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlanAnnotations {
    #[serde(rename = "DesiredTgUpdates", skip_serializing_if = "Option::is_none")]
    pub desired_tg_updates: Option<::std::collections::HashMap<String, crate::models::DesiredUpdates>>,
    #[serde(rename = "PreemptedAllocs", skip_serializing_if = "Option::is_none")]
    pub preempted_allocs: Option<Vec<crate::models::AllocationListStub>>,
}

impl PlanAnnotations {
    pub fn new() -> PlanAnnotations {
        PlanAnnotations {
            desired_tg_updates: None,
            preempted_allocs: None,
        }
    }
}


