/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaUsage {
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "Used", skip_serializing_if = "Option::is_none")]
    pub used: Option<::std::collections::HashMap<String, crate::models::QuotaLimit>>,
    #[serde(rename = "CreateIndex", skip_serializing_if = "Option::is_none")]
    pub create_index: Option<i32>,
    #[serde(rename = "ModifyIndex", skip_serializing_if = "Option::is_none")]
    pub modify_index: Option<i32>,
}

impl QuotaUsage {
    pub fn new() -> QuotaUsage {
        QuotaUsage {
            name: None,
            used: None,
            create_index: None,
            modify_index: None,
        }
    }
}


