/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotaLimit {
    #[serde(rename = "Region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(rename = "RegionLimit", skip_serializing_if = "Option::is_none")]
    pub region_limit: Option<Box<crate::models::Resources>>,
    #[serde(rename = "Hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
}

impl QuotaLimit {
    pub fn new() -> QuotaLimit {
        QuotaLimit {
            region: None,
            region_limit: None,
            hash: None,
        }
    }
}


