/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RaftServer {
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub ID: Option<String>,
    #[serde(rename = "Node", skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    #[serde(rename = "Address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "Leader", skip_serializing_if = "Option::is_none")]
    pub leader: Option<bool>,
    #[serde(rename = "Voter", skip_serializing_if = "Option::is_none")]
    pub voter: Option<bool>,
    #[serde(rename = "RaftProtocol", skip_serializing_if = "Option::is_none")]
    pub raft_protocol: Option<String>,
}

impl RaftServer {
    pub fn new() -> RaftServer {
        RaftServer {
            ID: None,
            node: None,
            address: None,
            leader: None,
            voter: None,
            raft_protocol: None,
        }
    }
}


