/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RescheduleEvent {
    #[serde(rename = "RescheduleTime", skip_serializing_if = "Option::is_none")]
    pub reschedule_time: Option<i64>,
    #[serde(rename = "PrevAllocID", skip_serializing_if = "Option::is_none")]
    pub prev_alloc_id: Option<String>,
    #[serde(rename = "PrevNodeID", skip_serializing_if = "Option::is_none")]
    pub prev_node_id: Option<String>,
}

impl RescheduleEvent {
    pub fn new() -> RescheduleEvent {
        RescheduleEvent {
            reschedule_time: None,
            prev_alloc_id: None,
            prev_node_id: None,
        }
    }
}


