/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Resources {
    #[serde(rename = "CPU", skip_serializing_if = "Option::is_none")]
    pub CPU: Option<i32>,
    #[serde(rename = "Cores", skip_serializing_if = "Option::is_none")]
    pub cores: Option<i32>,
    #[serde(rename = "MemoryMB", skip_serializing_if = "Option::is_none")]
    pub memory_mb: Option<i32>,
    #[serde(rename = "MemoryMaxMB", skip_serializing_if = "Option::is_none")]
    pub memory_max_mb: Option<i32>,
    #[serde(rename = "DiskMB", skip_serializing_if = "Option::is_none")]
    pub disk_mb: Option<i32>,
    #[serde(rename = "Networks", skip_serializing_if = "Option::is_none")]
    pub networks: Option<Vec<crate::models::NetworkResource>>,
    #[serde(rename = "Devices", skip_serializing_if = "Option::is_none")]
    pub devices: Option<Vec<crate::models::RequestedDevice>>,
    #[serde(rename = "IOPS", skip_serializing_if = "Option::is_none")]
    pub IOPS: Option<i32>,
}

impl Resources {
    pub fn new() -> Resources {
        Resources {
            CPU: None,
            cores: None,
            memory_mb: None,
            memory_max_mb: None,
            disk_mb: None,
            networks: None,
            devices: None,
            IOPS: None,
        }
    }
}


