/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceUsage {
    #[serde(rename = "MemoryStats", skip_serializing_if = "Option::is_none")]
    pub memory_stats: Option<Box<crate::models::MemoryStats>>,
    #[serde(rename = "CpuStats", skip_serializing_if = "Option::is_none")]
    pub cpu_stats: Option<Box<crate::models::CpuStats>>,
    #[serde(rename = "DeviceStats", skip_serializing_if = "Option::is_none")]
    pub device_stats: Option<Vec<crate::models::DeviceGroupStats>>,
}

impl ResourceUsage {
    pub fn new() -> ResourceUsage {
        ResourceUsage {
            memory_stats: None,
            cpu_stats: None,
            device_stats: None,
        }
    }
}


