/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchedulerConfiguration {
    #[serde(rename = "PreemptionConfig", skip_serializing_if = "Option::is_none")]
    pub preemption_config: Option<Box<crate::models::PreemptionConfig>>,
    #[serde(rename = "CreateIndex", skip_serializing_if = "Option::is_none")]
    pub create_index: Option<i32>,
    #[serde(rename = "ModifyIndex", skip_serializing_if = "Option::is_none")]
    pub modify_index: Option<i32>,
}

impl SchedulerConfiguration {
    pub fn new() -> SchedulerConfiguration {
        SchedulerConfiguration {
            preemption_config: None,
            create_index: None,
            modify_index: None,
        }
    }
}


