/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceCheck {
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub ID: Option<String>,
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "Type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "Command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    #[serde(rename = "Args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<String>>,
    #[serde(rename = "Path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "Protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "PortLabel", skip_serializing_if = "Option::is_none")]
    pub port_label: Option<String>,
    #[serde(rename = "AddressMode", skip_serializing_if = "Option::is_none")]
    pub address_mode: Option<String>,
    #[serde(rename = "Interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<i64>,
    #[serde(rename = "Timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i64>,
    #[serde(rename = "InitialStatus", skip_serializing_if = "Option::is_none")]
    pub initial_status: Option<String>,
    #[serde(rename = "TlsSkipVerify", skip_serializing_if = "Option::is_none")]
    pub tls_skip_verify: Option<bool>,
    #[serde(rename = "Header", skip_serializing_if = "Option::is_none")]
    pub header: Option<::std::collections::HashMap<String, Vec<String>>>,
    #[serde(rename = "Method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    #[serde(rename = "CheckRestart", skip_serializing_if = "Option::is_none")]
    pub check_restart: Option<Box<crate::models::CheckRestart>>,
    #[serde(rename = "GrpcService", skip_serializing_if = "Option::is_none")]
    pub grpc_service: Option<String>,
    #[serde(rename = "GrpcUseTls", skip_serializing_if = "Option::is_none")]
    pub grpc_use_tls: Option<bool>,
    #[serde(rename = "TaskName", skip_serializing_if = "Option::is_none")]
    pub task_name: Option<String>,
}

impl ServiceCheck {
    pub fn new() -> ServiceCheck {
        ServiceCheck {
            ID: None,
            name: None,
            _type: None,
            command: None,
            args: None,
            path: None,
            protocol: None,
            port_label: None,
            address_mode: None,
            interval: None,
            timeout: None,
            initial_status: None,
            tls_skip_verify: None,
            header: None,
            method: None,
            check_restart: None,
            grpc_service: None,
            grpc_use_tls: None,
            task_name: None,
        }
    }
}


