/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Service {
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub ID: Option<String>,
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "Tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "CanaryTags", skip_serializing_if = "Option::is_none")]
    pub canary_tags: Option<Vec<String>>,
    #[serde(rename = "EnableTagOverride", skip_serializing_if = "Option::is_none")]
    pub enable_tag_override: Option<bool>,
    #[serde(rename = "PortLabel", skip_serializing_if = "Option::is_none")]
    pub port_label: Option<String>,
    #[serde(rename = "AddressMode", skip_serializing_if = "Option::is_none")]
    pub address_mode: Option<String>,
    #[serde(rename = "Checks", skip_serializing_if = "Option::is_none")]
    pub checks: Option<Vec<crate::models::ServiceCheck>>,
    #[serde(rename = "CheckRestart", skip_serializing_if = "Option::is_none")]
    pub check_restart: Option<Box<crate::models::CheckRestart>>,
    #[serde(rename = "Connect", skip_serializing_if = "Option::is_none")]
    pub connect: Option<Box<crate::models::ConsulConnect>>,
    #[serde(rename = "Meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "CanaryMeta", skip_serializing_if = "Option::is_none")]
    pub canary_meta: Option<::std::collections::HashMap<String, String>>,
}

impl Service {
    pub fn new() -> Service {
        Service {
            ID: None,
            name: None,
            tags: None,
            canary_tags: None,
            enable_tag_override: None,
            port_label: None,
            address_mode: None,
            checks: None,
            check_restart: None,
            connect: None,
            meta: None,
            canary_meta: None,
        }
    }
}


