/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpreadTarget {
    #[serde(rename = "Value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "Percent", skip_serializing_if = "Option::is_none")]
    pub percent: Option<i32>,
}

impl SpreadTarget {
    pub fn new() -> SpreadTarget {
        SpreadTarget {
            value: None,
            percent: None,
        }
    }
}


