/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskGroupScaleStatus {
    #[serde(rename = "Desired", skip_serializing_if = "Option::is_none")]
    pub desired: Option<i32>,
    #[serde(rename = "Placed", skip_serializing_if = "Option::is_none")]
    pub placed: Option<i32>,
    #[serde(rename = "Running", skip_serializing_if = "Option::is_none")]
    pub running: Option<i32>,
    #[serde(rename = "Healthy", skip_serializing_if = "Option::is_none")]
    pub healthy: Option<i32>,
    #[serde(rename = "Unhealthy", skip_serializing_if = "Option::is_none")]
    pub unhealthy: Option<i32>,
    #[serde(rename = "Events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<crate::models::ScalingEvent>>,
}

impl TaskGroupScaleStatus {
    pub fn new() -> TaskGroupScaleStatus {
        TaskGroupScaleStatus {
            desired: None,
            placed: None,
            running: None,
            healthy: None,
            unhealthy: None,
            events: None,
        }
    }
}


