/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskGroupSummary {
    #[serde(rename = "Queued", skip_serializing_if = "Option::is_none")]
    pub queued: Option<i32>,
    #[serde(rename = "Complete", skip_serializing_if = "Option::is_none")]
    pub complete: Option<i32>,
    #[serde(rename = "Failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<i32>,
    #[serde(rename = "Running", skip_serializing_if = "Option::is_none")]
    pub running: Option<i32>,
    #[serde(rename = "Starting", skip_serializing_if = "Option::is_none")]
    pub starting: Option<i32>,
    #[serde(rename = "Lost", skip_serializing_if = "Option::is_none")]
    pub lost: Option<i32>,
}

impl TaskGroupSummary {
    pub fn new() -> TaskGroupSummary {
        TaskGroupSummary {
            queued: None,
            complete: None,
            failed: None,
            running: None,
            starting: None,
            lost: None,
        }
    }
}


