/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Template {
    #[serde(rename = "SourcePath", skip_serializing_if = "Option::is_none")]
    pub source_path: Option<String>,
    #[serde(rename = "DestPath", skip_serializing_if = "Option::is_none")]
    pub dest_path: Option<String>,
    #[serde(rename = "EmbeddedTmpl", skip_serializing_if = "Option::is_none")]
    pub embedded_tmpl: Option<String>,
    #[serde(rename = "ChangeMode", skip_serializing_if = "Option::is_none")]
    pub change_mode: Option<String>,
    #[serde(rename = "ChangeSignal", skip_serializing_if = "Option::is_none")]
    pub change_signal: Option<String>,
    #[serde(rename = "Splay", skip_serializing_if = "Option::is_none")]
    pub splay: Option<i64>,
    #[serde(rename = "Perms", skip_serializing_if = "Option::is_none")]
    pub perms: Option<String>,
    #[serde(rename = "LeftDelim", skip_serializing_if = "Option::is_none")]
    pub left_delim: Option<String>,
    #[serde(rename = "RightDelim", skip_serializing_if = "Option::is_none")]
    pub right_delim: Option<String>,
    #[serde(rename = "Envvars", skip_serializing_if = "Option::is_none")]
    pub envvars: Option<bool>,
    #[serde(rename = "VaultGrace", skip_serializing_if = "Option::is_none")]
    pub vault_grace: Option<i64>,
}

impl Template {
    pub fn new() -> Template {
        Template {
            source_path: None,
            dest_path: None,
            embedded_tmpl: None,
            change_mode: None,
            change_signal: None,
            splay: None,
            perms: None,
            left_delim: None,
            right_delim: None,
            envvars: None,
            vault_grace: None,
        }
    }
}


