/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateStrategy {
    #[serde(rename = "Stagger", skip_serializing_if = "Option::is_none")]
    pub stagger: Option<i64>,
    #[serde(rename = "MaxParallel", skip_serializing_if = "Option::is_none")]
    pub max_parallel: Option<i32>,
    #[serde(rename = "HealthCheck", skip_serializing_if = "Option::is_none")]
    pub health_check: Option<String>,
    #[serde(rename = "MinHealthyTime", skip_serializing_if = "Option::is_none")]
    pub min_healthy_time: Option<i64>,
    #[serde(rename = "HealthyDeadline", skip_serializing_if = "Option::is_none")]
    pub healthy_deadline: Option<i64>,
    #[serde(rename = "ProgressDeadline", skip_serializing_if = "Option::is_none")]
    pub progress_deadline: Option<i64>,
    #[serde(rename = "Canary", skip_serializing_if = "Option::is_none")]
    pub canary: Option<i32>,
    #[serde(rename = "AutoRevert", skip_serializing_if = "Option::is_none")]
    pub auto_revert: Option<bool>,
    #[serde(rename = "AutoPromote", skip_serializing_if = "Option::is_none")]
    pub auto_promote: Option<bool>,
}

impl UpdateStrategy {
    pub fn new() -> UpdateStrategy {
        UpdateStrategy {
            stagger: None,
            max_parallel: None,
            health_check: None,
            min_healthy_time: None,
            healthy_deadline: None,
            progress_deadline: None,
            canary: None,
            auto_revert: None,
            auto_promote: None,
        }
    }
}


