/*
 * Nomad
 *
 * Nomad OpenApi specification
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VolumeMount {
    #[serde(rename = "Volume", skip_serializing_if = "Option::is_none")]
    pub volume: Option<String>,
    #[serde(rename = "Destination", skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    #[serde(rename = "ReadOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    #[serde(rename = "PropagationMode", skip_serializing_if = "Option::is_none")]
    pub propagation_mode: Option<String>,
}

impl VolumeMount {
    pub fn new() -> VolumeMount {
        VolumeMount {
            volume: None,
            destination: None,
            read_only: None,
            propagation_mode: None,
        }
    }
}


